### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by mmaelicke** [jlewis91/dwdbulk#5]
Hey there,
Thanks for this nice repository. I was just wondering if there is any specific reason to restrict the dependencies to the versions specified in `setup.py`? Some of them are rather outdated and I would prefer to keep my pandas stable release, than downgrading to `0.25`.

Other question:  does 'comprehensive' from the Readme also  include `grid_data`, like the Radolan products made available on the CDC server (e.g. https://opendata.dwd.de/climate_environment/CDC/grids_germany/hourly/radolan/recent/asc/) ?

Thanks

**Comment by amotl** [comment]
Dear Mirko,

we just wanted to mention that we integrated Jeremiahs code to acquire MOSMIX data into [Wetterdienst](https://pypi.org/project/wetterdienst/) through https://github.com/earthobservations/wetterdienst/pull/114 just recently.

RADOLAN support has also been integrated the other day through https://github.com/earthobservations/wetterdienst/pull/129 and there are more things to come, see https://github.com/earthobservations/wetterdienst/pull/140.

You might also be interested that @kmuehlbauer, one of the authors and maintainer of [wradlib](https://github.com/wradlib), also joined our conversation at https://github.com/earthobservations/wetterdienst/issues/50#issuecomment-688057897.

You can find respective documentation about how to use Wetterdienst to acquire MOSMIX data at [1,2] and about RADOLAN data at [3,4].

We hope you will also be able to move on to Wetterdienst and we will be happy to receive any feedback about issues or ideas for improvements.

With kind regards,
Andreas.

[1] https://wetterdienst.readthedocs.io/en/latest/pages/api.html#mosmix
[2] https://github.com/earthobservations/wetterdienst/blob/v0.8.0/example/mosmix.py
[3] https://wetterdienst.readthedocs.io/en/latest/pages/api.html#radolan
[4] https://github.com/earthobservations/wetterdienst/blob/v0.8.0/example/radolan.py

cc @gutzbenj, @meteoDaniel

**Comment by mmaelicke** [comment]
hey @amotl, 
thanks for all this info. Yes, I have moved to Wetterdienst already, and therefore can close this issue. 
Thanks and best,
Mirko
